/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RyanGUIProject3;
import my.zhugui3.ZhuGUI3;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ZhuGUI3.main(args);
    }
}
